version: '3'

services:

  app:
    image: petclinic-app
    ports:
      -  8080:8080 
    environment:
      - MYSQL_URL=jdbc:mysql://db:3306/petclinic
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    depends_on:
      - db
    command: bash -c "sleep 10 && java -Dspring.profiles.active=mysql -jar ./app.jar"

  db:
    image: mysql:5.7
    ports:
      - 3306:3306 
    environment:
      - MYSQL_ROOT_PASSWORD= 
      - MYSQL_ALLOW_EMPTY_PASSWORD=true 
      - MYSQL_USER=petclinic 
      - MYSQL_PASSWORD=petclinic 
      - MYSQL_DATABASE=petclinic 
    volumes:
      - ./conf.d:/etc/mysql/conf.d:ro
      - ./mysql:/var/lib/mysql
